# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
# Recipes must be in a subdirectory: recipes-foo/pkgname/pkgname_ver.bb
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-medtech"
BBFILE_PATTERN_meta-medtech = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-medtech = "6"

# Keep dependency list explicit so CI only provisions required layers.
LAYERDEPENDS_meta-medtech = "core openembedded-layer networking-layer qt6-layer"
LAYERSERIES_COMPAT_meta-medtech = "kirkstone langdale scarthgap"
