#!/bin/bash
# DEPRECATED: generate-sbom.sh
#
# SBOM generation has migrated to Yocto's native create-spdx class.
# The bitbake build now produces standards-compliant SPDX 2.2 documents
# automatically via INHERIT += "create-spdx" in local.conf.
#
# Use scripts/process-sbom.sh after a successful bitbake build to collect
# the SPDX outputs into the sbom/ directory.

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "NOTE: generate-sbom.sh is deprecated."
echo "SBOM is now generated by Yocto's create-spdx class during the bitbake build."
echo "Run scripts/process-sbom.sh after 'bitbake core-image-medtech' to collect outputs."
exec "$SCRIPT_DIR/process-sbom.sh"
